### ISSUE TITLE
Invitation to move to official `eslint-community` org

### ISSUE THREAD

**Issue by MichaelDeBoey** [eslint-community/eslint-stylistic#252]
@antfu We would love to have this repo added to the official [`@eslint-community` organization on GitHub](https://github.com/eslint-community) as we appreciate all you've done and you're welcome to join the organization if you like.

As you can read in [the '`@eslint-community` GitHub organization' RFC](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org), the goal of this new org is to have a place where community members can help ensure widely depended upon ESLint related packages stay up to date with newer ESLint releases and doesn't hold the wider community back without depending on one person's GitHub/`npm` account.

Since this repo is maintaining previous core ESLint rules & rules from `@typescript-eslint/eslint-plugin` & `eslint-plugin-react` (which are both widely depended upon ESLint related packages), I think this package is a good candidate to be in the official @eslint-community org.

**Comment by antfu** [comment]
Thanks for the offer @MichaelDeBoey! I personally would love to, if the rest of the @eslint-stylistic/team also agree.

Here I have a few questions:
- Org names, we already have npm orgs `@stylistic` and `@eslint-stylistic`, I am thinking to keep them as-is, as they will make the rule name simple and explicit like `@stylistic/indent`. Is that ok with `eslint-community`?
- Teams, we already have a few team members on this project (I guess many of them might overlaps with eslint-community already). If I'd still lead the project, I would need so permission to moderate the team members as a sub-team in eslint-community maybe?
- Branding, since we have our own logos and docs site, what do you think we should move forward, keep it as-is or doing something? IMO a good branding could help ppl to recognize the project.
- Any other things you think we should do to align with eslint-community? This project's setup is indeed quite opinionated to my own preference that I believe would benefit the long term maintainability, but I understand that might not always fit with other philosophies

**Comment by MichaelDeBoey** [comment]
> * Org names, we already have npm orgs `@stylistic` and `@eslint-stylistic`, I am thinking to keep them as-is, as they will make the rule name simple and explicit like `@stylistic/indent`. Is that ok with `eslint-community`?

npm package can be called whatever it's called  
We try to keep the original name as much as possible

> Teams, we already have a few team members on this project (I guess many of them might overlaps with eslint-community already).

We can create a team on the community org with the same members and everybody can keep doing the same things

> Branding, since we have our own logos and docs site, what do you think we should move forward, keep it as-is or doing something? IMO a good branding could help ppl to recognize the project.

We can keep the current docs sites and logos

> Any other things you think we should do to align with eslint-community? This project's setup is indeed quite opinionated to my own preference that I believe would benefit the long term maintainability, but I understand that might not always fit with other philosophies

We have a few things that needs to be done in order to get everything fully working, but nothing that requires a lot of work

**Comment by kecrily** [comment]
I have no objections to joining the `eslint-community`, which now contains practically all active contributors to the ESLint ecosystem. I'm confident this will assist the program as well.

---

And sorry for taking so long to reply.

**Comment by MichaelDeBoey** [comment]
Closing as the repo is now moved to the @eslint-community org
